title: Dados Sae's Blog
f_tittle: Any question? Contact me!
author: Dados Sae
email: cp.hikmawan@gmail.com
twitter_username: cphikmawan
github_username: cphikmawan
youtube_username: "dados sae"
youtube_channel: "channel/UCkKgfIZLikOqmX_3kElsvpw/"
linkedin_username: cphikmawan
description: >-
baseurl: ""
url: "https://cloudy.my.id"

google_analytics: UA-158105644-1

markdown: kramdown
theme: minima
plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  
paginate: 5

about: Laku ing sasmita, amrih lantip lan memayu hayunin bawana
# Seorang yang ingin berilmu harus mengasah lahir dan batinnya
# Menambah indahnya dunia yang memang sudah diciptakan sedemikian indahnya

pre-commit:
  - check: FrontMatterVariableExists
    variables: ['title', 'author', 'date', 'tags', 'categories']
  - check: FrontMatterVariableIsNotDuplicate
    variables: ['title']
  - check: FrontMatterVariableMeetsLengthRequirements
    variables: ['title']
  - check: NoDuplicateTags

defaults:
  -
    scope:
      path: "_posts/*"
    values:
      sitemap: false
  - 
    scope:
      path: "CHANGELOG.md"
    values:
      sitemap: false