title: Dados Sae's Blog
f_tittle: Any question? Contact me!
author: Dados Sae
email: cloudhour9@gmail.com
description: >-
baseurl: ""
url: "https://cloudy.my.id"

markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-paginate

paginate: 5

about: Laku ing sasmita, amrih lantip lan memayu hayunin bawana
# Seorang yang ingin berilmu harus mengasah lahir dan batinnya
# Menambah indahnya dunia yang memang sudah diciptakan sedemikian indahnya

pre-commit:
  - check: FrontMatterVariableExists
    variables: ['description', 'image']
  - check: FrontMatterVariableIsNotDuplicate
    variables: ['description']
  - check: FrontMatterVariableMeetsLengthRequirements
    variables: ['description', 'title']
  - check: NoDuplicateTags
